# SPDX-License-Identifier: GPL-3.0-or-later
if(NOT DEFINED SOURCE_DIR OR NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "Specify SOURCE_DIR and OUTPUT_FILE")
endif()
set(BLENDER_PLATFORM_ARM ON)
include("${SOURCE_DIR}/build_files/build_environment/cmake/versions.cmake")
file(READ "${SOURCE_DIR}/build_files/build_environment/cmake/download.cmake" download_recipe)
string(REGEX MATCH "set\\(BLENDER_VERSION +([0-9]+\\.[0-9]+)\\)" version_match "${download_recipe}")
if(version_match)
  set(mirror_branch "blender-v${CMAKE_MATCH_1}-release")
else()
  set(mirror_branch "main")
endif()
get_cmake_property(all_vars VARIABLES)
file(WRITE "${OUTPUT_FILE}" "name\tversion\tfile\thash_type\thash\tblender_mirror\tupstream\n")
foreach(v ${all_vars})
  if(v MATCHES "^(.+)_FILE$")
    set(dep "${CMAKE_MATCH_1}")
    if(DEFINED ${dep}_HASH AND DEFINED ${dep}_URI)
      file(APPEND "${OUTPUT_FILE}" "${dep}\t${${dep}_VERSION}\t${${v}}\t${${dep}_HASH_TYPE}\t${${dep}_HASH}\thttps://projects.blender.org/blender/lib-source/media/branch/${mirror_branch}/${${v}}\t${${dep}_URI}\n")
    endif()
  endif()
endforeach()
